#list
list =[1,2,3,4]
print(list)
print ("_____________")
list .append(6)
print(list)
print ("_____________")
list.insert(4,5)
print(list)
print ("_____________")
list.remove(6)
print(list)
print ("_____________")
list.pop()
print(list)
print ("_____________")
list.reverse()
print(list)
print ("_____________")
print(list.count(3))